on: [push]
name: owasp
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
      - run: npm ci
      - run: npm install
      - run: npm run build --if-present
      - run: serve -s build
      
      - name: install npm
        run: npm install
      - name: build
        run: npm run build
      - name: install serve
        run: npm install -g serve 
      - name: serve build
        run: serve -s build

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://www.zaproxy.org/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
